---
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: pod-info-container
          image: firsttestcontainer.azurecr.io/accounts:latest
          ports:
            - containerPort: 9006
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets: 
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: development
spec:
  selector:
    app: accounts
  ports:
    - port: 80
      targetPort: 9006
  type: LoadBalancer
