
trigger:
  branches:
    include:
      - main
      - test


pool:
  name: 'default'

variables:
  BASE_GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  IMAGE_NAME: eureka
  K8S_NAMESPACE_DEVELOPMENT: development
  K8S_NAMESPACE_PRODUCTION: production
  DEPLOYMENT_NAME: eureka

stages:
  - stage: Build_And_Test
    jobs:
      - job: Building_Docker
        displayName: 'Building Docker'
        steps:
          - script: |
              sudo apt-get update
              sudo apt-get install -y openjdk-11-jdk
              echo "##vso[task.prependpath]/usr/lib/jvm/java-11-openjdk-amd64/bin"
              java -version
            displayName: 'Set up Java'
          - script: |
              chmod +x ./Backend/eureka_service/gradlew
            displayName: 'Make gradlew executable'
          - script: |
              cd Backend/eureka_service
              export GRADLE_USER_HOME=$(BASE_GRADLE_USER_HOME)/Backend/eureka_service
              ./gradlew build
            displayName: 'Build with Gradle'
          - script: |
              cd Backend/eureka_service
              export GRADLE_USER_HOME=$(BASE_GRADLE_USER_HOME)/Backend/eureka_service
              ./gradlew test
            displayName: 'Run tests with Gradle'
          - task: Docker@2
            inputs:
              containerRegistry: 'testings'
              repository: '$(IMAGE_NAME)'
              command: 'buildAndPush'
              Dockerfile: 'Backend/eureka_service/Dockerfile'  # Corrected Dockerfile path
              tags: |
                latest
                $(Build.BuildId)

  - stage: Deploy_to_Staging
    dependsOn: Build_And_Test
    jobs:
      - job: Deploy_to_Staging_Job
        displayName: 'Deploy to Staging'
        steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'workings'
              namespace: '$(K8S_NAMESPACE_DEVELOPMENT)'
              manifests: |
                $(Build.SourcesDirectory)/Backend/eureka_service/deployment.yaml
              containers: |
                $(IMAGE_NAME):$(Build.BuildId)
              arguments: '--validate=false'

  - stage: Deploy_to_Production
    dependsOn: Deploy_to_Staging
    jobs:

      - deployment: Deploy_to_Production_Job
        displayName: 'Deploy to Production'
        environment: 'new'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'workings'
                    namespace: '$(K8S_NAMESPACE_PRODUCTION)'
                    manifests: |
                      $(Build.SourcesDirectory)/Backend/eureka_service/k8service.yaml
                    containers: |
                      $(IMAGE_NAME):$(Build.BuildId)

