---
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: pod-info-container
          image: firsttestcontainer.azurecr.io/eureka:latest
          ports:
            - containerPort: 9001
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets: 
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: development
spec:
  selector:
    app: eureka
  ports:
    - port: 80
      targetPort: 9001
  type: LoadBalancer
