server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
