---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-config
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-config
  template:
    metadata:
      labels:
        app: system-config
    spec:
      containers:
        - name: pod-info-container
          image: firsttestcontainer.azurecr.io/system:latest
          ports:
            - containerPort: 9003
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: system-config-service
  namespace: production
spec:
  selector:
    app: system-config
  ports:
    - port: 80
      targetPort: 9003
  type: LoadBalancer
