---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      containers:
        - name: pod-info-container
          image: firsttestcontainer.azurecr.io/test:241
          ports:
            - containerPort: 2024
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets: 
        - name: acr-secret

        
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: production
spec:
  selector:
    app: pod-info
  ports:
    - port: 80
      targetPort: 2024
  type: LoadBalancer


