---
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: pod-info-container
          image: firsttestcontainer.azurecr.io/api:latest
          ports:
            - containerPort: 9002
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets: 
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: development
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 9002
  type: LoadBalancer
