variables:
  projectPath: '/home/kiplangat/Documents/run-devops/new/TESTDEVS/Frontend/ClientMain'

trigger:
  branches:
    include:
      - main
      - test

pool:
  name: 'default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    cd $(projectPath)
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'Build Angular application'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(projectPath)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: 'Copy Files to Artifact Staging Directory'

- script: ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'List contents of Artifact Staging Directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/drop'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
    replaceExistingArchive: true
  displayName: 'Archive Build Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop.zip'
    ArtifactName: 'drop'
  displayName: 'Publish Build Artifacts'

# - task: DownloadPipelineArtifact@2
#   inputs:
#     buildType: 'current'
#     artifactName: 'drop'
#     targetPath: '$(Build.ArtifactStagingDirectory)'
#   displayName: 'Download Build Artifacts'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'frontpipelines'
    appType: 'webAppLinux'  # Changed to indicate Linux web app
    WebAppName: 'microFs'
    package: '$(Build.ArtifactStagingDirectory)/drop.zip'
  displayName: 'Deploy to Azure Web App'
  