server:
  port: 9002
  tomcat:
    access-log-enabled: true

#KAFKA PROPERTIES
auto:
  create:
    topics:
      enable: 'true'
topic:
  name:
    producer: application.mails

spring:
  application:
    useOTP: false
    otpProd: false
    otpTestMail: ckibet@emtechhouse.co.ke
    logs:
      user: C:\Users\Francis\Desktop\POST BANK\EMT_009_Sacco_Solution\Server\api_gateway_service\src\main\resources\Userlogs\user.log
    name: API-GATEWAY
    enableEmail: true
    client:
      origin_local: http://localhost:4201/
      origin_52: http://localhost:4201/

    basicActions: /home/kiplangat/Documents/run_devops/TESTDEVS/Backend/api_gateway_service/basicactions.json

    service:
      account_statement_download_path: C:/Users/Francis/Downloads/



  #KAFKA PROPERTIES spring.application.enableEmail

  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
  #  session:
  #    store-type: redis
  #    redis:
  #      flush-mode: on-save
  #  redis:
  #    host: localhost
  #    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/ayact_africa
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
#    dbname: emt_multitenant_sacco
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:mariadb://52.15.152.26:3306/goodway_sacco_prod2
#    username: emtech
#    password: emtech@2022
#    driverClassName: org.mariadb.jdbc.Driver#

  #EMAIL CONFIGURATIONS
  mail:
    protocol: smtps
    host: mail.francis-mugambi.me.ke
    port: 465
    username: info@francis-mugambi.me.ke
    password: FRANKMUGAH97@g
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: mail.francis-mugambi.me.ke
  organisation:
    emailRegards: Post Bank Sacco
    emailMessage: Find the attached information from our partnership
    emailOrganizationName: Post Bank Sacco
    name: Entity

    image_banner: C:\Users\dell\EMTECH\POST BANK\EMT_MULTITENANT_SACCO\Server\api_gateway_service\src\main\resources\PBlogo.png
    emailRemarks: Thank You.
    emailOrganizationLocation: Head Office Plot 4/6 Nkrumah Road, Kampala.
    emailOrganizationPhone: +256 ** *** ***
    emailOrganizationWebsite: =://postbank.co.ug
    emailOrganizationMail: mail@=.co.ug
    emailOrganizationAddress: P.O.Box 7189, Kampala.

    from_mail: info@francis-mugambi.me.ke
    company_logo_path: /home/dnyiri/Documents/EMTech-Projects/EMT_MULTITENANT_SACCO/Server/eureka_service/src/main/resources/logo.png

    emailSalutation: Dear Sir/Madam,
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true  # This property is important for avoiding some potential hostname-related issues


users:
  app:
    jwtSecret: /buCOEjS/+H7ZwekxyLKLdDeegHUGEytjxuivosdrzjRG4g4E+kA3uXO5lvGBVsl2NwqsgiGUUI5bjgY/6WG/VSIIG+22b1Rvdb59BY0YRod6Dnjnp0REsPn//hshs6ucnOVCBRp0lbVb1kP+EDOM7W7N72/+t+R1d8JQ4pjisoJZI4e0MV3PlZtzXKI0SY2EQUtI
    jwtExpirationMs: 43200000

organisation:
  email: info@francis-mugambi.me.ke

  #  Super User Details
  superUserEmail: info@francis.me.ke
  superUserFirstName: Superuser
  superUserLastName: Admin
  superUserUserName: Superuser
  superUserPhone: 07xxxxxxxx
  superUserSolCode: 000
  superUserPassword: SuPassCode12
  maxNoOfTellers: 20


  zuul:
    host:
      connect-timeout-millis: 2000
      socket-timeout-millis: 5000

    routes:
      system-config-service:
        sensitiveHeaders:
        url: http://localhost:9003

      products-service:
        sensitiveHeaders:
        url: http://localhost:9004

      crm-service:
        sensitiveHeaders:
        url: http://localhost:9005

      accounts-service:
        sensitiveHeaders:
        url: http://localhost:9006

      transaction-service:
        sensitiveHeaders:
        url: http://localhost:9007

      reports-service:
        sensitiveHeaders:
        url: http://localhost:9008

      channel-support-service:
        sensitiveHeaders:
        url: http://localhost:2024

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
